### ISSUE TITLE
Questions about the bulk motion algorithm

### ISSUE THREAD

**Issue by sunningzh** [markstock/dla-nd#1]
Hi,

I am interested in the DLA simulation and find your code very helpful to understand the DLA. However, I just cannot understand how the bulk motion algorithm in your code:

rad^2 = ( v\*dt + sdev\*(\sqrt{dt}) )^2,

and why not let:

rad^2 = ( v\*dt + sdev\*dt )^2.

I just do not understand why we need a  numeric root-finder \sqrt{dt} here. Could you provide some explanations?

Thank you,
sunningzh

**Comment by markstock** [comment]
Hi - thanks for digging into the code. I assume you are looking at code around main.c, line 627.

If I remember correctly, the challenge with bulk motion is that the bulk motion is linear in time, while diffusion lengths scale as the square root of time. So, given a radius around a diffusing particle, inside of which there is no part of the DLA structure, we must find the minimum average time required for that particle to reach that radius (presumably mostly along the axis of bulk motion, but not exactly). That involves a component from movement by linear time, and a component due to diffusion, which must scale by the square root of time.

If I used the term "std deviation" incorrectly, then I apologize for the confusion. And it's also very likely that this algorithm is incorrect, or introduces some error. It was the best that I could do at the time to get particles to take large steps that were mostly correct.

Does this clear the confusion up?

**Comment by sunningzh** [comment]
Thank you for your quick reply and patience. Your answer is very clear and I have understood this algorithm. Actually I didn't realize the time-scale relationship before.
